ColorScheme: System
Language: en
Theme: Win11Light
ShowOpenResultHotkey: true
WindowSize: 580
UseGlyphIcons: true
UseAnimation: true
UseSound: true
SoundVolume: 20
UseClock: true
UseDate: false
TimeFormat: hh:mm tt
DateFormat: MM'/'dd ddd
FirstLaunch: false
ShowBadges: false
ShowBadgesGlobalOnly: false
BackdropType: 0
MaxHistoryResultsToShowForHomePage: 5
ShowPlaceholder: true
PlaceholderText: ""
ShowHomePage: true
ShowHistoryResultsForHomePage: false
AutoRestartAfterChanging: false
ShowUnknownSourceWarning: true
LogLevel: INFO
UseLogonTaskForStartup: false
HideWhenDeactivated: true
SearchQueryResultsWithDelay: false
SearchDelayTime: 150
CustomScreenNumber: 1
CustomAnimationLength: 360
ShouldUsePinyin: false
AlwaysPreview: false
AlwaysStartEn: false
QuerySearchPrecision: Regular
AutoUpdates: true
CustomWindowLeft: 0
CustomWindowTop: 0
KeepMaxResults: false
MaxResultsToShow: 9
DontPromptUpdateMsg: false
EnableUpdateLog: false
StartFlowLauncherOnSystemStartup: true
HideOnStartup: true
HideNotifyIcon: false
LeaveCmdOpen: false
SearchWindowScreen: Primary
SearchWindowAlign: Center
IgnoreHotkeysOnFullscreen: false
LastQueryMode: Empty
AnimationSpeed: Fast

Hotkey: Alt + Space
PreviewHotkey: F1
OpenResultModifiers: Alt
AutoCompleteHotkey: Tab
AutoCompleteHotkey2: ""
SelectNextItemHotkey: Alt + J
SelectNextItemHotkey2: Ctrl + J
SelectPrevItemHotkey: Alt + K
SelectPrevItemHotkey2: Ctrl + K
SelectNextPageHotkey: PageUp
SelectPrevPageHotkey: PageDown
OpenContextMenuHotkey: Ctrl + O
SettingWindowHotkey: Ctrl + I
CycleHistoryUpHotkey: Alt + Up
CycleHistoryDownHotkey: Alt + Down
OpenHistoryHotkey: Ctrl+H
CustomPluginHotkeys: []
CustomShortcuts: []

UseDropShadowEffect: true
WindowHeightSize: 42
ItemHeightSize: 58
QueryBoxFont: Microsoft Sans Serif
QueryBoxFontSize: 20
QueryBoxFontStyle: null
QueryBoxFontWeight: null
QueryBoxFontStretch: null
ResultFont: Microsoft Sans Serif
ResultFontStyle: null
ResultFontWeight: null
ResultFontStretch: null
ResultItemFontSize: 16
ResultSubFont: Microsoft Sans Serif
ResultSubFontStyle: null
ResultSubFontWeight: null
ResultSubFontStretch: null
ResultSubItemFontSize: 13
SettingWindowFont: Segoe UI

SettingWindowWidth: 1000
SettingWindowHeight: 700
SettingWindowTop: 146
SettingWindowLeft: 460
SettingWindowState: 0

CustomExplorerIndex: 3
CustomExplorerList:
  - Name: Explorer
    Path: explorer
    FileArgument: /select, "%f"
    DirectoryArgument: '"%d"'
    Editable: false

  - Name: "Total Commander"
    Path: C:\Program Files\totalcmd\TOTALCMD64.exe
    FileArgument: /O /A /S /T "%f"
    DirectoryArgument: /O /A /S /T "%d"
    Editable: true

  - Name: Directory Opus
    Path: C:\Program Files\GPSoftware\Directory Opus\dopusrt.exe
    FileArgument: /cmd Go "%f" NEW
    DirectoryArgument: /cmd Go "%d" NEW
    Editable: true

  - Name: Files
    Path: Files
    FileArgument: -select "%f"
    DirectoryArgument: -select "%d"
    Editable: true
CustomBrowserIndex: 3
CustomBrowserList:
  - Name: Default
    Path: '*'
    PrivateArg: ""
    EnablePrivate: false
    OpenInTab: true
    Editable: false

  - Name: Google Chrome
    Path: chrome
    PrivateArg: -incognito
    EnablePrivate: false
    OpenInTab: true
    Editable: false

  - Name: Mozilla Firefox
    Path: firefox
    PrivateArg: -private
    EnablePrivate: false
    OpenInTab: true
    Editable: false

  - Name: MS Edge
    Path: msedge
    PrivateArg: -inPrivate
    EnablePrivate: false
    OpenInTab: true
    Editable: false

  - Name: Brave
    Path: brave
    PrivateArg: --incognito
    EnablePrivate: false
    OpenInTab: true
    Editable: false

Proxy:
  Enabled: false
  Server: null
  Port: 0
  UserName: null
  Password: null

PluginSettings:
  NodeExecutablePath: ""
  Plugins:
    0ECADE17459B49F587BF81DC3A125110:
      ID: 0ECADE17459B49F587BF81DC3A125110
      Name: Browser Bookmarks
      Version: '3.3.4'
      ActionKeywords:
        - b
      Priority: 0
      Disabled: false
    CEA0FDFC6D3B4085823D60DC76F28855:
      ID: CEA0FDFC6D3B4085823D60DC76F28855
      Name: Calculator
      Version: '3.1.5'
      ActionKeywords:
        - '*'
      Priority: 0
      Disabled: false
    572be03c74c642baae319fc283e561a8:
      ID: 572be03c74c642baae319fc283e561a8
      Name: Explorer
      Version: '3.2.4'
      ActionKeywords:
        - '*'
        - 'doc:'
        - '*'
        - '*'
        - '*'
      Priority: 0
      Disabled: false

    6A122269676E40EB86EB543B945932B9:
      ID: 6A122269676E40EB86EB543B945932B9
      Name: Plugin Indicator
      Version: '3.0.7'
      ActionKeywords:
        - '*'
      Priority: 0
      Disabled: false

    9f8f9b14-2518-4907-b211-35ab6290dee7:
      ID: 9f8f9b14-2518-4907-b211-35ab6290dee7
      Name: Plugins Manager
      Version: '3.2.4'
      ActionKeywords:
        - pm
      Priority: 0
      Disabled: false
    b64d0a79-329a-48b0-b53f-d658318a1bf6:
      ID: b64d0a79-329a-48b0-b53f-d658318a1bf6
      Name: Process Killer
      Version: '3.0.8'
      ActionKeywords:
        - kill
      Priority: 0
      Disabled: false

    791FC278BA414111B8D1886DFE447410:
      ID: 791FC278BA414111B8D1886DFE447410
      Name: Program
      Version: '3.3.4'
      ActionKeywords:
        - '*'
      Priority: 0
      Disabled: false

    D409510CD0D2481F853690A07E6DC426:
      ID: D409510CD0D2481F853690A07E6DC426
      Name: Shell
      Version: '3.2.5'
      ActionKeywords:
        - '>'
      Priority: 0
      Disabled: false
    CEA08895D2544B019B2E9C5009600DF4:
      ID: CEA08895D2544B019B2E9C5009600DF4
      Name: System Commands
      Version: '3.1.7'
      ActionKeywords:
        - '*'
      Priority: 0
      Disabled: false

    0308FD86DE0A4DEE8D62B9B535370992:
      ID: 0308FD86DE0A4DEE8D62B9B535370992
      Name: URL
      Version: '3.0.8'
      ActionKeywords:
        - '*'
      Priority: 0
      Disabled: false

    565B73353DBF4806919830B9202EE3BF:
      ID: 565B73353DBF4806919830B9202EE3BF
      Name: Web Searches
      Version: '3.1.4'
      ActionKeywords:
        - '*'
        - sc
        - wiki
        - findicon
        - facebook
        - twitter
        - maps
        - translate
        - duckduckgo
        - github
        - gist
        - gmail
        - drive
        - wolframalpha
        - stackoverflow
        - lucky
        - image
        - youtube
        - bing
        - yahoo
        - bd
      Priority: 0
      Disabled: false

    5043CETYU6A748679OPA02D27D99677A:
      ID: 5043CETYU6A748679OPA02D27D99677A
      Name: Windows Settings
      Version: '4.0.12'
      ActionKeywords:
        - s
      Priority: 0
      Disabled: false

    F737A9223560B3C6833B5FFB8CDF78E5:
      ID: F737A9223560B3C6833B5FFB8CDF78E5
      Name: Window Walker
      Version: '3.0.3'
      ActionKeywords:
        - sw
      Priority: 0
      Disabled: false

# These aren't copied since they're pretty frequently changed
WindowLeft: 960
WindowTop: 247.5
PreviousScreenWidth: 0
PreviousScreenHeight: 0
PreviousDpiX: 0
PreviousDpiY: 0
ActivateTimes: 81